---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxy.trafiks.io
  resources:
  - trafiksbackends
  - trafiksproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.trafiks.io
  resources:
  - trafiksbackends/finalizers
  - trafiksproxies/finalizers
  verbs:
  - update
- apiGroups:
  - proxy.trafiks.io
  resources:
  - trafiksbackends/status
  - trafiksproxies/status
  verbs:
  - get
  - patch
  - update
