// Code generated by MockGen. DO NOT EDIT.
// Source: api_key.go
//
// Generated by this command:
//
//	mockgen -source=api_key.go -destination=../../tests/mocks/api_key.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/trafiks/trafiks/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAPIKeyRepoClient is a mock of APIKeyRepoClient interface.
type MockAPIKeyRepoClient struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyRepoClientMockRecorder
	isgomock struct{}
}

// MockAPIKeyRepoClientMockRecorder is the mock recorder for MockAPIKeyRepoClient.
type MockAPIKeyRepoClientMockRecorder struct {
	mock *MockAPIKeyRepoClient
}

// NewMockAPIKeyRepoClient creates a new mock instance.
func NewMockAPIKeyRepoClient(ctrl *gomock.Controller) *MockAPIKeyRepoClient {
	mock := &MockAPIKeyRepoClient{ctrl: ctrl}
	mock.recorder = &MockAPIKeyRepoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyRepoClient) EXPECT() *MockAPIKeyRepoClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAPIKeyRepoClient) Create(ctx context.Context, apiKey *models.APIKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, apiKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAPIKeyRepoClientMockRecorder) Create(ctx, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAPIKeyRepoClient)(nil).Create), ctx, apiKey)
}

// Delete mocks base method.
func (m *MockAPIKeyRepoClient) Delete(ctx context.Context, filter *models.APIKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAPIKeyRepoClientMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAPIKeyRepoClient)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockAPIKeyRepoClient) Find(ctx context.Context, filter *models.APIKey) (*models.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filter)
	ret0, _ := ret[0].(*models.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAPIKeyRepoClientMockRecorder) Find(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAPIKeyRepoClient)(nil).Find), ctx, filter)
}

// FindMany mocks base method.
func (m *MockAPIKeyRepoClient) FindMany(ctx context.Context, filter *models.APIKey) ([]*models.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", ctx, filter)
	ret0, _ := ret[0].([]*models.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockAPIKeyRepoClientMockRecorder) FindMany(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockAPIKeyRepoClient)(nil).FindMany), ctx, filter)
}

// Updates mocks base method.
func (m *MockAPIKeyRepoClient) Updates(ctx context.Context, filter *models.APIKey, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, filter, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockAPIKeyRepoClientMockRecorder) Updates(ctx, filter, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockAPIKeyRepoClient)(nil).Updates), ctx, filter, updates)
}
