// Code generated by MockGen. DO NOT EDIT.
// Source: docker.go
//
// Generated by this command:
//
//	mockgen -source=docker.go -destination=../../tests/mocks/docker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
