// Code generated by MockGen. DO NOT EDIT.
// Source: kubernetes.go
//
// Generated by this command:
//
//	mockgen -source=kubernetes.go -destination=../../tests/mocks/kubernetes.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
