// Code generated by MockGen. DO NOT EDIT.
// Source: project.go
//
// Generated by this command:
//
//	mockgen -source=project.go -destination=../../tests/mocks/project.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/trafiks/trafiks/api/dto"
	models "github.com/trafiks/trafiks/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectRepoClient is a mock of ProjectRepoClient interface.
type MockProjectRepoClient struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepoClientMockRecorder
	isgomock struct{}
}

// MockProjectRepoClientMockRecorder is the mock recorder for MockProjectRepoClient.
type MockProjectRepoClientMockRecorder struct {
	mock *MockProjectRepoClient
}

// NewMockProjectRepoClient creates a new mock instance.
func NewMockProjectRepoClient(ctrl *gomock.Controller) *MockProjectRepoClient {
	mock := &MockProjectRepoClient{ctrl: ctrl}
	mock.recorder = &MockProjectRepoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepoClient) EXPECT() *MockProjectRepoClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectRepoClient) Create(ctx context.Context, project *models.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectRepoClientMockRecorder) Create(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectRepoClient)(nil).Create), ctx, project)
}

// Delete mocks base method.
func (m *MockProjectRepoClient) Delete(ctx context.Context, filter *models.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectRepoClientMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectRepoClient)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockProjectRepoClient) Find(ctx context.Context, filter *models.Project) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filter)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockProjectRepoClientMockRecorder) Find(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProjectRepoClient)(nil).Find), ctx, filter)
}

// FindMany mocks base method.
func (m *MockProjectRepoClient) FindMany(ctx context.Context, filter *models.Project, pagination *dto.Pagination) ([]*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", ctx, filter, pagination)
	ret0, _ := ret[0].([]*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockProjectRepoClientMockRecorder) FindMany(ctx, filter, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockProjectRepoClient)(nil).FindMany), ctx, filter, pagination)
}

// Updates mocks base method.
func (m *MockProjectRepoClient) Updates(ctx context.Context, filter *models.Project, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, filter, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockProjectRepoClientMockRecorder) Updates(ctx, filter, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockProjectRepoClient)(nil).Updates), ctx, filter, updates)
}
