// Code generated by MockGen. DO NOT EDIT.
// Source: proxy_request_log.go
//
// Generated by this command:
//
//	mockgen -source=proxy_request_log.go -destination=../../tests/mocks/proxy_request_log.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/trafiks/trafiks/api/dto"
	repository "github.com/trafiks/trafiks/api/repository"
	models "github.com/trafiks/trafiks/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProxyRequestLogRepoClient is a mock of ProxyRequestLogRepoClient interface.
type MockProxyRequestLogRepoClient struct {
	ctrl     *gomock.Controller
	recorder *MockProxyRequestLogRepoClientMockRecorder
	isgomock struct{}
}

// MockProxyRequestLogRepoClientMockRecorder is the mock recorder for MockProxyRequestLogRepoClient.
type MockProxyRequestLogRepoClientMockRecorder struct {
	mock *MockProxyRequestLogRepoClient
}

// NewMockProxyRequestLogRepoClient creates a new mock instance.
func NewMockProxyRequestLogRepoClient(ctrl *gomock.Controller) *MockProxyRequestLogRepoClient {
	mock := &MockProxyRequestLogRepoClient{ctrl: ctrl}
	mock.recorder = &MockProxyRequestLogRepoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyRequestLogRepoClient) EXPECT() *MockProxyRequestLogRepoClientMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockProxyRequestLogRepoClient) Count(ctx context.Context, filter *models.ProxyRequestLog, filters *repository.RequestLogFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockProxyRequestLogRepoClientMockRecorder) Count(ctx, filter, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockProxyRequestLogRepoClient)(nil).Count), ctx, filter, filters)
}

// Create mocks base method.
func (m *MockProxyRequestLogRepoClient) Create(ctx context.Context, log *models.ProxyRequestLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProxyRequestLogRepoClientMockRecorder) Create(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProxyRequestLogRepoClient)(nil).Create), ctx, log)
}

// Find mocks base method.
func (m *MockProxyRequestLogRepoClient) Find(ctx context.Context, filter *models.ProxyRequestLog) (*models.ProxyRequestLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filter)
	ret0, _ := ret[0].(*models.ProxyRequestLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockProxyRequestLogRepoClientMockRecorder) Find(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProxyRequestLogRepoClient)(nil).Find), ctx, filter)
}

// FindMany mocks base method.
func (m *MockProxyRequestLogRepoClient) FindMany(ctx context.Context, filter *models.ProxyRequestLog, pagination *dto.Pagination, filters *repository.RequestLogFilters) ([]*models.ProxyRequestLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", ctx, filter, pagination, filters)
	ret0, _ := ret[0].([]*models.ProxyRequestLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockProxyRequestLogRepoClientMockRecorder) FindMany(ctx, filter, pagination, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockProxyRequestLogRepoClient)(nil).FindMany), ctx, filter, pagination, filters)
}

// GetMethodsByProjectID mocks base method.
func (m *MockProxyRequestLogRepoClient) GetMethodsByProjectID(ctx context.Context, projectID uint, filters *repository.RequestLogFilters) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMethodsByProjectID", ctx, projectID, filters)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMethodsByProjectID indicates an expected call of GetMethodsByProjectID.
func (mr *MockProxyRequestLogRepoClientMockRecorder) GetMethodsByProjectID(ctx, projectID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMethodsByProjectID", reflect.TypeOf((*MockProxyRequestLogRepoClient)(nil).GetMethodsByProjectID), ctx, projectID, filters)
}

// GetMetricsByProjectID mocks base method.
func (m *MockProxyRequestLogRepoClient) GetMetricsByProjectID(ctx context.Context, projectID uint, filters *repository.RequestLogFilters) (*repository.MetricsAggregation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsByProjectID", ctx, projectID, filters)
	ret0, _ := ret[0].(*repository.MetricsAggregation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricsByProjectID indicates an expected call of GetMetricsByProjectID.
func (mr *MockProxyRequestLogRepoClientMockRecorder) GetMetricsByProjectID(ctx, projectID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsByProjectID", reflect.TypeOf((*MockProxyRequestLogRepoClient)(nil).GetMetricsByProjectID), ctx, projectID, filters)
}

// GetStatusCodesByProjectID mocks base method.
func (m *MockProxyRequestLogRepoClient) GetStatusCodesByProjectID(ctx context.Context, projectID uint, filters *repository.RequestLogFilters) (map[int]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusCodesByProjectID", ctx, projectID, filters)
	ret0, _ := ret[0].(map[int]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusCodesByProjectID indicates an expected call of GetStatusCodesByProjectID.
func (mr *MockProxyRequestLogRepoClientMockRecorder) GetStatusCodesByProjectID(ctx, projectID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusCodesByProjectID", reflect.TypeOf((*MockProxyRequestLogRepoClient)(nil).GetStatusCodesByProjectID), ctx, projectID, filters)
}

// GetTimeSeriesByProjectID mocks base method.
func (m *MockProxyRequestLogRepoClient) GetTimeSeriesByProjectID(ctx context.Context, projectID uint, filters *repository.RequestLogFilters, groupBy string) ([]repository.TimeSeriesPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeSeriesByProjectID", ctx, projectID, filters, groupBy)
	ret0, _ := ret[0].([]repository.TimeSeriesPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeSeriesByProjectID indicates an expected call of GetTimeSeriesByProjectID.
func (mr *MockProxyRequestLogRepoClientMockRecorder) GetTimeSeriesByProjectID(ctx, projectID, filters, groupBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeSeriesByProjectID", reflect.TypeOf((*MockProxyRequestLogRepoClient)(nil).GetTimeSeriesByProjectID), ctx, projectID, filters, groupBy)
}

// GetTopPathsByProjectID mocks base method.
func (m *MockProxyRequestLogRepoClient) GetTopPathsByProjectID(ctx context.Context, projectID uint, filters *repository.RequestLogFilters, limit int) ([]repository.PathAggregation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopPathsByProjectID", ctx, projectID, filters, limit)
	ret0, _ := ret[0].([]repository.PathAggregation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopPathsByProjectID indicates an expected call of GetTopPathsByProjectID.
func (mr *MockProxyRequestLogRepoClientMockRecorder) GetTopPathsByProjectID(ctx, projectID, filters, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopPathsByProjectID", reflect.TypeOf((*MockProxyRequestLogRepoClient)(nil).GetTopPathsByProjectID), ctx, projectID, filters, limit)
}
