// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../../tests/mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/trafiks/trafiks/models"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceRepoClient is a mock of ServiceRepoClient interface.
type MockServiceRepoClient struct {
	ctrl     *gomock.Controller
	recorder *MockServiceRepoClientMockRecorder
	isgomock struct{}
}

// MockServiceRepoClientMockRecorder is the mock recorder for MockServiceRepoClient.
type MockServiceRepoClientMockRecorder struct {
	mock *MockServiceRepoClient
}

// NewMockServiceRepoClient creates a new mock instance.
func NewMockServiceRepoClient(ctrl *gomock.Controller) *MockServiceRepoClient {
	mock := &MockServiceRepoClient{ctrl: ctrl}
	mock.recorder = &MockServiceRepoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceRepoClient) EXPECT() *MockServiceRepoClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockServiceRepoClient) Create(ctx context.Context, service *models.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockServiceRepoClientMockRecorder) Create(ctx, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockServiceRepoClient)(nil).Create), ctx, service)
}

// Delete mocks base method.
func (m *MockServiceRepoClient) Delete(ctx context.Context, filter *models.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceRepoClientMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceRepoClient)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockServiceRepoClient) Find(ctx context.Context, filter *models.Service) (*models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filter)
	ret0, _ := ret[0].(*models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockServiceRepoClientMockRecorder) Find(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockServiceRepoClient)(nil).Find), ctx, filter)
}

// FindByProjectSlug mocks base method.
func (m *MockServiceRepoClient) FindByProjectSlug(ctx context.Context, projectSlug string) (*models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectSlug", ctx, projectSlug)
	ret0, _ := ret[0].(*models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectSlug indicates an expected call of FindByProjectSlug.
func (mr *MockServiceRepoClientMockRecorder) FindByProjectSlug(ctx, projectSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectSlug", reflect.TypeOf((*MockServiceRepoClient)(nil).FindByProjectSlug), ctx, projectSlug)
}

// FindMany mocks base method.
func (m *MockServiceRepoClient) FindMany(ctx context.Context, filter *models.Service) ([]*models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", ctx, filter)
	ret0, _ := ret[0].([]*models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockServiceRepoClientMockRecorder) FindMany(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockServiceRepoClient)(nil).FindMany), ctx, filter)
}

// Updates mocks base method.
func (m *MockServiceRepoClient) Updates(ctx context.Context, filter *models.Service, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, filter, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockServiceRepoClientMockRecorder) Updates(ctx, filter, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockServiceRepoClient)(nil).Updates), ctx, filter, updates)
}
