// Code generated by MockGen. DO NOT EDIT.
// Source: source.go
//
// Generated by this command:
//
//	mockgen -source=source.go -destination=../../tests/mocks/source.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/trafiks/trafiks/models"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceSource is a mock of ServiceSource interface.
type MockServiceSource struct {
	ctrl     *gomock.Controller
	recorder *MockServiceSourceMockRecorder
	isgomock struct{}
}

// MockServiceSourceMockRecorder is the mock recorder for MockServiceSource.
type MockServiceSourceMockRecorder struct {
	mock *MockServiceSource
}

// NewMockServiceSource creates a new mock instance.
func NewMockServiceSource(ctrl *gomock.Controller) *MockServiceSource {
	mock := &MockServiceSource{ctrl: ctrl}
	mock.recorder = &MockServiceSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceSource) EXPECT() *MockServiceSourceMockRecorder {
	return m.recorder
}

// Enabled mocks base method.
func (m *MockServiceSource) Enabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockServiceSourceMockRecorder) Enabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockServiceSource)(nil).Enabled))
}

// Get mocks base method.
func (m *MockServiceSource) Get(ctx context.Context, proxyURL string) (*models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, proxyURL)
	ret0, _ := ret[0].(*models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceSourceMockRecorder) Get(ctx, proxyURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceSource)(nil).Get), ctx, proxyURL)
}

// Name mocks base method.
func (m *MockServiceSource) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockServiceSourceMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockServiceSource)(nil).Name))
}
