// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=../../tests/mocks/user.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/trafiks/trafiks/models"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockUserRepoClient is a mock of UserRepoClient interface.
type MockUserRepoClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoClientMockRecorder
	isgomock struct{}
}

// MockUserRepoClientMockRecorder is the mock recorder for MockUserRepoClient.
type MockUserRepoClientMockRecorder struct {
	mock *MockUserRepoClient
}

// NewMockUserRepoClient creates a new mock instance.
func NewMockUserRepoClient(ctrl *gomock.Controller) *MockUserRepoClient {
	mock := &MockUserRepoClient{ctrl: ctrl}
	mock.recorder = &MockUserRepoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepoClient) EXPECT() *MockUserRepoClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepoClient) Create(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepoClientMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepoClient)(nil).Create), ctx, user)
}

// CreateWithCB mocks base method.
func (m *MockUserRepoClient) CreateWithCB(ctx context.Context, user *models.User, cb func(*gorm.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithCB", ctx, user, cb)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithCB indicates an expected call of CreateWithCB.
func (mr *MockUserRepoClientMockRecorder) CreateWithCB(ctx, user, cb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithCB", reflect.TypeOf((*MockUserRepoClient)(nil).CreateWithCB), ctx, user, cb)
}

// Find mocks base method.
func (m *MockUserRepoClient) Find(ctx context.Context, filter *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filter)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserRepoClientMockRecorder) Find(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserRepoClient)(nil).Find), ctx, filter)
}

// Updates mocks base method.
func (m *MockUserRepoClient) Updates(ctx context.Context, filter *models.User, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, filter, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockUserRepoClientMockRecorder) Updates(ctx, filter, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockUserRepoClient)(nil).Updates), ctx, filter, updates)
}
