// Code generated by MockGen. DO NOT EDIT.
// Source: webhook_delivery.go
//
// Generated by this command:
//
//	mockgen -source=webhook_delivery.go -destination=../../tests/mocks/webhook_delivery.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/trafiks/trafiks/api/dto"
	repository "github.com/trafiks/trafiks/api/repository"
	models "github.com/trafiks/trafiks/models"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookDeliveryRepoClient is a mock of WebhookDeliveryRepoClient interface.
type MockWebhookDeliveryRepoClient struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookDeliveryRepoClientMockRecorder
	isgomock struct{}
}

// MockWebhookDeliveryRepoClientMockRecorder is the mock recorder for MockWebhookDeliveryRepoClient.
type MockWebhookDeliveryRepoClientMockRecorder struct {
	mock *MockWebhookDeliveryRepoClient
}

// NewMockWebhookDeliveryRepoClient creates a new mock instance.
func NewMockWebhookDeliveryRepoClient(ctrl *gomock.Controller) *MockWebhookDeliveryRepoClient {
	mock := &MockWebhookDeliveryRepoClient{ctrl: ctrl}
	mock.recorder = &MockWebhookDeliveryRepoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookDeliveryRepoClient) EXPECT() *MockWebhookDeliveryRepoClientMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockWebhookDeliveryRepoClient) Count(ctx context.Context, filter *models.WebhookDelivery, filters *repository.WebhookDeliveryFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockWebhookDeliveryRepoClientMockRecorder) Count(ctx, filter, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockWebhookDeliveryRepoClient)(nil).Count), ctx, filter, filters)
}

// Create mocks base method.
func (m *MockWebhookDeliveryRepoClient) Create(ctx context.Context, delivery *models.WebhookDelivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, delivery)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWebhookDeliveryRepoClientMockRecorder) Create(ctx, delivery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWebhookDeliveryRepoClient)(nil).Create), ctx, delivery)
}

// Find mocks base method.
func (m *MockWebhookDeliveryRepoClient) Find(ctx context.Context, filter *models.WebhookDelivery) (*models.WebhookDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filter)
	ret0, _ := ret[0].(*models.WebhookDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockWebhookDeliveryRepoClientMockRecorder) Find(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockWebhookDeliveryRepoClient)(nil).Find), ctx, filter)
}

// FindMany mocks base method.
func (m *MockWebhookDeliveryRepoClient) FindMany(ctx context.Context, filter *models.WebhookDelivery, pagination *dto.Pagination, filters *repository.WebhookDeliveryFilters) ([]*models.WebhookDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", ctx, filter, pagination, filters)
	ret0, _ := ret[0].([]*models.WebhookDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockWebhookDeliveryRepoClientMockRecorder) FindMany(ctx, filter, pagination, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockWebhookDeliveryRepoClient)(nil).FindMany), ctx, filter, pagination, filters)
}

// FindPending mocks base method.
func (m *MockWebhookDeliveryRepoClient) FindPending(ctx context.Context, filter *models.WebhookDelivery, limit int) ([]*models.WebhookDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPending", ctx, filter, limit)
	ret0, _ := ret[0].([]*models.WebhookDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPending indicates an expected call of FindPending.
func (mr *MockWebhookDeliveryRepoClientMockRecorder) FindPending(ctx, filter, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPending", reflect.TypeOf((*MockWebhookDeliveryRepoClient)(nil).FindPending), ctx, filter, limit)
}

// FindRetryable mocks base method.
func (m *MockWebhookDeliveryRepoClient) FindRetryable(ctx context.Context, limit int) ([]*models.WebhookDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRetryable", ctx, limit)
	ret0, _ := ret[0].([]*models.WebhookDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRetryable indicates an expected call of FindRetryable.
func (mr *MockWebhookDeliveryRepoClientMockRecorder) FindRetryable(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRetryable", reflect.TypeOf((*MockWebhookDeliveryRepoClient)(nil).FindRetryable), ctx, limit)
}

// Update mocks base method.
func (m *MockWebhookDeliveryRepoClient) Update(ctx context.Context, delivery *models.WebhookDelivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, delivery)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWebhookDeliveryRepoClientMockRecorder) Update(ctx, delivery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWebhookDeliveryRepoClient)(nil).Update), ctx, delivery)
}

// Updates mocks base method.
func (m *MockWebhookDeliveryRepoClient) Updates(ctx context.Context, delivery *models.WebhookDelivery, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, delivery, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockWebhookDeliveryRepoClientMockRecorder) Updates(ctx, delivery, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockWebhookDeliveryRepoClient)(nil).Updates), ctx, delivery, updates)
}
