// Code generated by MockGen. DO NOT EDIT.
// Source: webhook.go
//
// Generated by this command:
//
//	mockgen -source=webhook.go -destination=../../tests/mocks/webhook_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/trafiks/trafiks/models"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookRepoClient is a mock of WebhookRepoClient interface.
type MockWebhookRepoClient struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookRepoClientMockRecorder
	isgomock struct{}
}

// MockWebhookRepoClientMockRecorder is the mock recorder for MockWebhookRepoClient.
type MockWebhookRepoClientMockRecorder struct {
	mock *MockWebhookRepoClient
}

// NewMockWebhookRepoClient creates a new mock instance.
func NewMockWebhookRepoClient(ctrl *gomock.Controller) *MockWebhookRepoClient {
	mock := &MockWebhookRepoClient{ctrl: ctrl}
	mock.recorder = &MockWebhookRepoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookRepoClient) EXPECT() *MockWebhookRepoClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWebhookRepoClient) Create(ctx context.Context, webhook *models.Webhook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, webhook)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWebhookRepoClientMockRecorder) Create(ctx, webhook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWebhookRepoClient)(nil).Create), ctx, webhook)
}

// Delete mocks base method.
func (m *MockWebhookRepoClient) Delete(ctx context.Context, webhook *models.Webhook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, webhook)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWebhookRepoClientMockRecorder) Delete(ctx, webhook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWebhookRepoClient)(nil).Delete), ctx, webhook)
}

// Find mocks base method.
func (m *MockWebhookRepoClient) Find(ctx context.Context, filter *models.Webhook) (*models.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filter)
	ret0, _ := ret[0].(*models.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockWebhookRepoClientMockRecorder) Find(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockWebhookRepoClient)(nil).Find), ctx, filter)
}

// FindMany mocks base method.
func (m *MockWebhookRepoClient) FindMany(ctx context.Context, filter *models.Webhook) ([]*models.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", ctx, filter)
	ret0, _ := ret[0].([]*models.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockWebhookRepoClientMockRecorder) FindMany(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockWebhookRepoClient)(nil).FindMany), ctx, filter)
}

// Update mocks base method.
func (m *MockWebhookRepoClient) Update(ctx context.Context, webhook *models.Webhook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, webhook)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWebhookRepoClientMockRecorder) Update(ctx, webhook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWebhookRepoClient)(nil).Update), ctx, webhook)
}
