// Code generated by MockGen. DO NOT EDIT.
// Source: webhook.go
//
// Generated by this command:
//
//	mockgen -source=webhook.go -destination=../../tests/mocks/webhook.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWebhookEventSender is a mock of WebhookEventSender interface.
type MockWebhookEventSender struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookEventSenderMockRecorder
	isgomock struct{}
}

// MockWebhookEventSenderMockRecorder is the mock recorder for MockWebhookEventSender.
type MockWebhookEventSenderMockRecorder struct {
	mock *MockWebhookEventSender
}

// NewMockWebhookEventSender creates a new mock instance.
func NewMockWebhookEventSender(ctrl *gomock.Controller) *MockWebhookEventSender {
	mock := &MockWebhookEventSender{ctrl: ctrl}
	mock.recorder = &MockWebhookEventSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookEventSender) EXPECT() *MockWebhookEventSenderMockRecorder {
	return m.recorder
}

// SendEvent mocks base method.
func (m *MockWebhookEventSender) SendEvent(webhookID uint, eventType string, data map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEvent", webhookID, eventType, data)
}

// SendEvent indicates an expected call of SendEvent.
func (mr *MockWebhookEventSenderMockRecorder) SendEvent(webhookID, eventType, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEvent", reflect.TypeOf((*MockWebhookEventSender)(nil).SendEvent), webhookID, eventType, data)
}
