{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trafiks-charts.fullname" . }}-backend
  labels:
    {{- include "trafiks-charts.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.tlsPort | default 8443 }}
      targetPort: {{ .Values.service.tlsTargetPort | default 8443 }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.tlsNodePort }}
      nodePort: {{ .Values.service.tlsNodePort }}
      {{- end }}
      protocol: TCP
      name: https
  selector:
    {{- include "trafiks-charts.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
