apiVersion: proxy.trafiks.io/v1
kind: TrafiksProxy
metadata:
  labels:
    app.kubernetes.io/name: trafiks-operator
    app.kubernetes.io/managed-by: kustomize
  name: trafiksproxy-sample
spec:
  # TODO(user): Add fields here
