// Code generated by MockGen. DO NOT EDIT.
// Source: trafiks_api_client.go
//
// Generated by this command:
//
//	mockgen -source=trafiks_api_client.go -destination=../test/mocks/trafiks_api_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTrafiksAPIClient is a mock of TrafiksAPIClient interface.
type MockTrafiksAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockTrafiksAPIClientMockRecorder
	isgomock struct{}
}

// MockTrafiksAPIClientMockRecorder is the mock recorder for MockTrafiksAPIClient.
type MockTrafiksAPIClientMockRecorder struct {
	mock *MockTrafiksAPIClient
}

// NewMockTrafiksAPIClient creates a new mock instance.
func NewMockTrafiksAPIClient(ctrl *gomock.Controller) *MockTrafiksAPIClient {
	mock := &MockTrafiksAPIClient{ctrl: ctrl}
	mock.recorder = &MockTrafiksAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrafiksAPIClient) EXPECT() *MockTrafiksAPIClientMockRecorder {
	return m.recorder
}

// CheckAuthentication mocks base method.
func (m *MockTrafiksAPIClient) CheckAuthentication(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAuthentication", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAuthentication indicates an expected call of CheckAuthentication.
func (mr *MockTrafiksAPIClientMockRecorder) CheckAuthentication(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAuthentication", reflect.TypeOf((*MockTrafiksAPIClient)(nil).CheckAuthentication), ctx)
}

// CheckHealth mocks base method.
func (m *MockTrafiksAPIClient) CheckHealth(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockTrafiksAPIClientMockRecorder) CheckHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockTrafiksAPIClient)(nil).CheckHealth), ctx)
}

// CreateProject mocks base method.
func (m *MockTrafiksAPIClient) CreateProject(ctx context.Context, name, description string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, name, description)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockTrafiksAPIClientMockRecorder) CreateProject(ctx, name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockTrafiksAPIClient)(nil).CreateProject), ctx, name, description)
}

// CreateService mocks base method.
func (m *MockTrafiksAPIClient) CreateService(ctx context.Context, projectUID string, serviceData map[string]any) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateService", ctx, projectUID, serviceData)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateService indicates an expected call of CreateService.
func (mr *MockTrafiksAPIClientMockRecorder) CreateService(ctx, projectUID, serviceData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateService", reflect.TypeOf((*MockTrafiksAPIClient)(nil).CreateService), ctx, projectUID, serviceData)
}

// DeleteProject mocks base method.
func (m *MockTrafiksAPIClient) DeleteProject(ctx context.Context, projectUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", ctx, projectUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockTrafiksAPIClientMockRecorder) DeleteProject(ctx, projectUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockTrafiksAPIClient)(nil).DeleteProject), ctx, projectUID)
}

// GetProject mocks base method.
func (m *MockTrafiksAPIClient) GetProject(ctx context.Context, projectUID string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, projectUID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockTrafiksAPIClientMockRecorder) GetProject(ctx, projectUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockTrafiksAPIClient)(nil).GetProject), ctx, projectUID)
}

// GetService mocks base method.
func (m *MockTrafiksAPIClient) GetService(ctx context.Context, projectUID, proxyURL string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", ctx, projectUID, proxyURL)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockTrafiksAPIClientMockRecorder) GetService(ctx, projectUID, proxyURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockTrafiksAPIClient)(nil).GetService), ctx, projectUID, proxyURL)
}

// ListProjects mocks base method.
func (m *MockTrafiksAPIClient) ListProjects(ctx context.Context) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockTrafiksAPIClientMockRecorder) ListProjects(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockTrafiksAPIClient)(nil).ListProjects), ctx)
}

// SetAPIConfig mocks base method.
func (m *MockTrafiksAPIClient) SetAPIConfig(baseURL, apiKey string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAPIConfig", baseURL, apiKey)
}

// SetAPIConfig indicates an expected call of SetAPIConfig.
func (mr *MockTrafiksAPIClientMockRecorder) SetAPIConfig(baseURL, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAPIConfig", reflect.TypeOf((*MockTrafiksAPIClient)(nil).SetAPIConfig), baseURL, apiKey)
}

// UpdateService mocks base method.
func (m *MockTrafiksAPIClient) UpdateService(ctx context.Context, projectUID, serviceUID string, serviceData map[string]any) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateService", ctx, projectUID, serviceUID, serviceData)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateService indicates an expected call of UpdateService.
func (mr *MockTrafiksAPIClientMockRecorder) UpdateService(ctx, projectUID, serviceUID, serviceData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateService", reflect.TypeOf((*MockTrafiksAPIClient)(nil).UpdateService), ctx, projectUID, serviceUID, serviceData)
}
