apiVersion: v1
kind: Secret
metadata:
  # Note: This secret name should match secrets.name in values.yaml
  name: trafiks-secrets
  namespace: trafiks
  labels:
    app: trafiks
type: Opaque
stringData:
  config.json: |
    {
      "log_level": "info",
      "log_output": "stdout",
      "server_port": "8889",
      "tls_port": "8443",
      "app_base_url": "trafikscloud.cloud",
      "environment": "production",
      "dashboard": {
        "enabled": true
      },
      "bootstrap": {
        "user": {
          "email": "admin@trafiks.local",
          "password": "admin123",
          "first_name": "admin",
          "last_name": "user"
        }
      },
      "database": {
        "host": "trafiks-postgresql",
        "port": 5432,
        "user": "postgres",
        "password": "postgres",
        "name": "trafiks",
        "ssl_mode": "disable",
        "log_enabled": false
      },
      "jwt_secret": "2pPLTGtIGEDhvIDPJBYp/c8gzV5bRacq9QE7pDpBEdM26AmONv0+6crsf+suz/Nn",
      "redis": {
        "host": "trafiks-redis-master:6379",
        "username": "",
        "password": "",
        "db": 0
      }
    }
