apiVersion: v1
kind: Secret
metadata:
  name: trafiks-secrets
  namespace: trafiks
  labels:
    app: trafiks
type: Opaque
stringData:
  config.json: |
    {
      "log_level": "info",
      "log_output": "stdout",
      "server_port": "8889",
      "tls_port": "8443",
      "app_base_url": "trafikscloud.cloud",
      "environment": "production",
      "dashboard": {
        "enabled": true
      },
      "bootstrap": {
        "user": {
          "email": "admin@trafiks.local",
          "password": "admin123",
          "first_name": "admin",
          "last_name": "user"
        }
      },
      "database": {
        "host": "trafiks-postgresql",
        "port": 5432,
        "user": "postgres",
        "password": "postgres",
        "name": "trafiks",
        "ssl_mode": "disable",
        "log_enabled": false
      },
      "jwt_secret": "2pPLTGtIGEDhvIDPJBYp/c8gzV5bRacq9QE7pDpBEdM26AmONv0+6crsf+suz/Nn",
      "redis": {
        "host": "trafiks-redis-master:6379",
        "username": "",
        "password": "",
        "db": 0
      }
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: trafiks-tls-secret
  namespace: trafiks
  labels:
    app: trafiks
type: Opaque
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDSTCCAjGgAwIBAgIUJ12EbNzhU5CfHB7xkQZ/fwEnyCkwDQYJKoZIhvcNAQEL
    BQAwNDEYMBYGA1UEAwwPdHJhZmZpa2VkLmNsb3VkMRgwFgYDVQQKDA90cmFmZmlr
    ZWQuY2xvdWQwHhcNMjUxMjE4MTcxNTMxWhcNMjYxMjE4MTcxNTMxWjA0MRgwFgYD
    VQQDDA90cmFmZmlrZWQuY2xvdWQxGDAWBgNVBAoMD3RyYWZmaWtlZC5jbG91ZDCC
    ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMfKZWKC4kbh+omLy6cKOryl
    z1w3UIWjbVekVLK8zcABd5JP/I0fUiQ5BuZ8TJzl0m83iJhmbISCpYuB9T/evrpQ
    +y+ztaszr388EGLUI+6sAW4FlH9HrzCJnV8AOvRD2MEUsc1YSn5IEN2j1ny0eQZP
    2g02pUemUjZ3QWEMT0vqgAUyCbngFt+twN5VetJnuerkKfWXeyaeypdV3wkoukVE
    5K3J2f++fLlX7/u9f79gvyCzd2TTML84323KfaTTzkuuwSaq5AcUAkU2DvlXlPEj
    wMBnSMP+HT9ndYg452zW+CNbn5JGgiqOcWSWUzfNKoC1kD+HxS9dI+ffa1GqMxUC
    AwEAAaNTMFEwHQYDVR0OBBYEFDx0PZGBgVk2H0hxwwKbiCMIWhtRMB8GA1UdIwQY
    MBaAFDx0PZGBgVk2H0hxwwKbiCMIWhtRMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI
    hvcNAQELBQADggEBAIPUmUOA0nEOs+4ElKr6jyRQDV6/hl3XHxsvjEdMjbSRm/3S
    8xlbxI2Krk+98xgCnfH70YWM1BVSoAjrfrpeKa2c9FlQAH/FBnzIfmQ0uCp7iPiw
    LL8Ck6tc/JE7cJ36s8ICk6QZrMbp+TBhc7QT4ou9iuFK7RwDLiKKLQG0XjepNtD0
    eJ0017OdltKbVevP1Za0RVdeL3YyeCO6laUld5phIW/WKm2gulzZ7RNwCY23DiEg
    XNz6vWqcoI1eetO6O35rBG9GZRO2ut8XKL13tKxXTendx+SDh7+YXHaEqb33oHIK
    +ZCU4LEku7P0fVqSbdx3g9PwtSr4sH+8ArAiW8Q=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDHymViguJG4fqJ
    i8unCjq8pc9cN1CFo21XpFSyvM3AAXeST/yNH1IkOQbmfEyc5dJvN4iYZmyEgqWL
    gfU/3r66UPsvs7WrM69/PBBi1CPurAFuBZR/R68wiZ1fADr0Q9jBFLHNWEp+SBDd
    o9Z8tHkGT9oNNqVHplI2d0FhDE9L6oAFMgm54BbfrcDeVXrSZ7nq5Cn1l3smnsqX
    Vd8JKLpFROStydn/vny5V+/7vX+/YL8gs3dk0zC/ON9tyn2k085LrsEmquQHFAJF
    Ng75V5TxI8DAZ0jD/h0/Z3WIOOds1vgjW5+SRoIqjnFkllM3zSqAtZA/h8UvXSPn
    32tRqjMVAgMBAAECggEAOUpvoj0X9+2LM3AT+RV03G3LtYzjGT9Q9oXYB90ePwXs
    rNck+67UljCIKwXPzloU6vGIyPLuAV2ZbRTaJ/OOy8y3CunEmZBbreeiZ0Sf/Svz
    yQHuoEUFFq0PpJNjVHI0MMHnbpP34Jh3xabata3m2omBZLKb2Jz4DEhMRjEKeCEH
    1WenSfUHvcgjtSf9RaDRtBDAJewg7t3/83uuTywGqM0svq4fgJl5RD4r15bGQGSZ
    tLTGHX9s4B3AfWOKz9LSV0J5wMMqLqwg/SgiYy7ZkEaQGHNb8Jh60HwJwC5XdR+r
    E5u0tkH1I9dXh5UwW9CA9R56jFTcJUAttLOKR3R/7QKBgQDmPBnM9u2Ml/EllEFo
    E/e1NphT4v6b4LgRohoxDGvy/z4zxinLkI7lvX5snzC0BWfbBTj1DazUoT75J2Mh
    3jX7Tbb/XOIl1lSu8pusJxjUaPU6RPy7IiYCIB6ZZY2BNAu6GoplmLIwbVg4RNuK
    CFjhxzVRX3o9PyVeAaL1TNezwwKBgQDeJh0CXnB0CbQPErjsBYC27HeySrdmt7N+
    Ba4Ur6wz3wggphdUNeDJrOrTXgo+bBVHNDI0m+uhQWYQdfHFFVD6zu7nBxyn4TCq
    eRH3iv+ThdnDe00R2U6/sPKaAsPsiwBkm8MDpoesLc4zJRZCUB80HpkjQI9Q2V6D
    zn1Q6Y3IRwKBgQCmoYjq1yxGPRHC6PINqaX1+XV2ASvVFWcjG/do2FyomiMixaEq
    O42wqNz/MJfHMsJfuf/nG+aiXbF+EgulT3YyU6TGXSsvx1ey5tPUXNeTpAMYESX5
    KlXn4+dBjkZD5K84Gk1gCouskPbwgqWB2Vi6z7q/EiMegL1CtFyEvQDAkQKBgD19
    FzJ8qWu0893oNL8/lq0LLuZuv+zylAAh2llndqa06S8AShzI/PtVnXn74aH9kLYw
    wGTHc6Ui0PllbBI9IDkL5hyUX14oeqv07wAxvSQ8PFZbXq2+FIoClGQEt+5VWzp9
    0rDD+3GxDA4kCdE5FCn8/i4/xGuAfyTElvM6ckApAoGALrKj1jU4WgxDWkk0xpe+
    63xXCkwOq1wMsdO/Fqy4Lgth6d32/wbBKt6ASfXNKtSKExzGGlv0ZBPlx27HiyCJ
    gpggI2zTdE3vIV6X+t7Lezh1UrpZzJlLkoN34SzH0FRmaUxH/y29Xqmv9xCvlwDn
    NgzRAUeFat1kVhLql7Q5BRs=
    -----END PRIVATE KEY-----
