version: '3.8'

services:
  redis_trafiks:
    image: redis:8
    container_name: redis_trafiks
    ports:
      - "6381:6379"
    volumes:
      - redis_trafiks-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    labels:
      - my-storage=redis_trafiks
    networks:
      - trafiks_network
  postgres_trafiks:
    image: postgres:latest
    container_name: postgres_trafiks
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trafiks
    ports:
      - "5436:5432"
    volumes:
      - postgres_trafiks-data:/var/lib/postgresql
    restart: always
    networks:
      - trafiks_network    
  trafiks-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: trafiks-backend
    ports:
      - "8889:8889"  # HTTP port
      - "8443:8443"  # HTTPS port
    restart: unless-stopped
    volumes:
      # Mount Docker socket for Docker source discovery
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /Users/olalekanodukoya/.colima/k8s/docker.sock:/var/run/docker.sock
      # Mount config file to default viper path: $HOME/.config/trafiks/config.json
      # We run as root in the container, so $HOME is /root
      - ./config.json:/root/.config/trafiks/config.json:ro
    networks:
      - trafiks_network
    depends_on:
      - postgres_trafiks
      - redis_trafiks

  trafiks-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: trafiks-agent
    restart: unless-stopped
    volumes:
      # Mount config file to default viper path: $HOME/.config/trafiks/config.json
      # We run as root in the container, so $HOME is /root
      - ./config.json:/root/.config/trafiks/config.json:ro
      # - /Users/olalekanodukoya/.colima/k8s/docker.sock:/var/run/docker.sock
      
    networks:
      - trafiks_network
    depends_on:
      - postgres_trafiks
      - redis_trafiks
      - trafiks-backend    

volumes:
  postgres_trafiks-data:
  redis_trafiks-data: 

networks:
  trafiks_network:
    external: true
    name: trafiks_network
